---
name: Run tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  buildAndTest:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt install -y clang libsubunit-dev check

      - name: Build
        run: |
          make

      - name: Test
        # Specifying the LDFLAGS is a workaround for issues with check on
        # Ubuntu
        run: |
          make LDFLAGS="`pkg-config --cflags --libs check`" test

  buildDocs:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install doxygen
        run: |
          sudo apt install -y doxygen

      - name: Build docs
        run: |
          doxygen

      - name: Preserve docs
        uses: actions/upload-artifact@v3
        with:
          path: docs/html/
          name: docs
